### ISSUE TITLE
Views should be editable in Blend.

### ISSUE THREAD

**Issue by a-einstein** [a-einstein/WpfTestApplication#1]
Blend reports 'invalid markup' on views containing text resources. This disables most of Blends functionality and should be solved.

Note that already on opening the solution the referred resource project causes an error that can be found in the migration report.

**Comment by a-einstein** [comment]
This seems like a nice first assignment to @Albert-O.

**Comment by BertMule** [comment]
Solved, see my commit and pull request.

**Comment by a-einstein** [comment]
Merged to master.
